version: '3.4'

networks:
  dev:
    driver: bridge

services:

  web: 
    depends_on:
      - bankapi
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - 4200:443
    networks:
      - dev   
    restart: 
      on-failure

#  proxy:
 #   depends_on:
#      - bankapi
 #     - web
  #  build:
   #   context: ./Proxy  
    #  dockerfile: Dockerfile
#    ports:
 #     - "443:443"

  bankapi:
    depends_on: 
      - postgres
    build:
      context: ./Backend/BankAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ConnectionStrings__Default: "Server=postgres;Database=SafeBankApi;Port=5432;User Id=postgres;Password=postgres;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
    networks:
      - dev
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    restart:
      on-failure

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=SafeBankApi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
    restart:
      on-failure
    
volumes:
  app_data: