version: '3.4'

services:
  web: 
    depends_on:
      - bankapi
    build:
      context: Frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    links:
      #- bankapi
      - proxy

  bankapi:
    depends_on: 
      - postgres
    image: ${DOCKER_REGISTRY-}bankapi
    container_name: services
    ports:
      - 8080:8080
    restart: always
    build:
      context: ./Backend/BankAPI
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Default=Server=postgres;Database=SafeBankApi;Port=5432;User Id=postgres;Password=postgres;
      - ASPNETCORE_URLS=http://+:8080
    links:
      - postgres

  proxy:
    depends_on: 
      - bankapi
    build: 
      context: ./Backend/proxy
      dockerfile: Dockerfile
    ports:
      - 8000:80
    links:
      - bankapi

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=SafeBankApi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    
volumes:
  app_data: